FROM jboss/infinispan-server:8.2.5.Final

MAINTAINER Vanei
LABEL description="Infinispan Server para o fluig" version="8.2"

#COPY standalone.xml /opt/jboss/infinispan-server/standalone/configuration/standalone.xml
COPY clustered.xml /opt/jboss/infinispan-server/standalone/configuration/clustered.xml
#COPY mgmt-users.properties /opt/jboss/infinispan-server/standalone/configuration/mgmt-users.properties
#COPY mgmt-users.properties /opt/jboss/infinispan-server/domain/configuration/mgmt-users.properties
#COPY mgmt-groups.properties /opt/jboss/infinispan-server/standalone/configuration/mgmt-groups.properties
#COPY mgmt-groups.properties /opt/jboss/infinispan-server/domain/configuration/mgmt-groups.properties
