FROM jboss/infinispan-server:8.2.5.Final

MAINTAINER Vanei
LABEL description="Infinispan Server para o fluig" version="8.2"

COPY standalone.xml /opt/jboss/infinispan-server/standalone/configuration/standalone.xml

